#!/bin/sh
### BEGIN INIT INFO
# Provides:          <NAME>
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>
### END INIT INFO

NAME=ExampleSrv
DAEMON=/home/thomas/c++/SrvLib/build/$NAME
RUNAS=root

PIDDIR=/var/run/$NAME
PIDFILE=$PIDDIR/$NAME.pid
LOGFILE=/var/log/$NAME.log

test -x $DAEMON || exit 0

start() {
  echo -n 'starting service…' >&2
  if ! start-stop-daemon --start --quiet --oknodo --exec $DAEMON --chuid $RUNAS
  then
    echo ' …service not started' >&2
    exit 1
  fi
  echo ' …service started' >&2
}

stop() {
  echo -n 'stopping service…' >&2
  start-stop-daemon --stop --quiet --exec $DAEMON
  sleep 1
  echo ' …service stopped' >&2
}

status() {
  echo -n 'checking…'
  if ! start-stop-daemon --status --exec $DAEMON
  then
    echo ' …service not started' >&2
  else
    echo ' …service started' >&2
  fi
}

install() {
  update-rc.d $(basename "$0") defaults
}

remove() {
  update-rc.d -f $(basename "$0") remove
}

reload() {
  echo -n 'reload configuratione…' >&2
  pkill -HUP $NAME
  sleep 1
  echo ' …configuration reloaded' >&2
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  restart)
    stop
    start
    ;;
  install)
    install
    ;;
  remove)
    remove
    ;;
  reload)
    reload
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|install|remove}"
esac

return 1
